netzkolchose/django-computedfields

- .travis.yml
- README.md
- computedfields/graph.py
- computedfields/models.py
- docs/conf.py
- docs/manual.rst
- example/requirements-dev.txt
- example/requirements-travis.txt
- example/test_full/models.py
- example/test_full/tests/test_updatefields.py
- setup.py
> fix partial updates with update_fields during save

- .travis.yml
- README.md
- computedfields/admin.py
- computedfields/helper.py
- computedfields/management/commands/createmap.py
- computedfields/models.py
- example/exampleapp/models.py
- example/test_full/tests/test_commands.py
- setup.py
the title says it all :-)
(I didn't run tests locally, will let travis do)
> django 3.0 compatibility

- computedfields/admin.py
Do not escape the pygments string.
> add mark_safe to pygments string, fixes #7

- computedfields/models.py
- example/test_full/models.py
- example/test_full/tests/test_abstract_model.py
> Support for computed fields on abstract models

- computedfields/graph.py
- docs/examples.rst
- docs/index.rst
- example/test_full/models.py
- example/test_full/tests/test_33.py
> autoexpand field dependencies on reverse relations

- computedfields/models.py
- example/test_full/models.py
- example/test_full/tests/test_abstract_model.py
This fixes https://github.com/netzkolchose/django-computedfields/issues/41
> Fix bug where computed fields of a model would leak to other models

- README.md
- computedfields/resolver.py
- docs/manual.rst
- example/test_full/models.py
- example/test_full/tests/test_simpletree.py
> fix recursion on empty queryset

- computedfields/graph.py
- computedfields/helper.py
- computedfields/resolver.py
- docs/examples.rst
- docs/manual.rst
- example/test_full/models.py
- example/test_full/tests/test_multitable.py
- example/test_full/tests/test_multitable_example.py
Testbed and playground PR for multi table tests.
@mobiware Plz ignore the failing tests (happens due to the debug logs not matching the expected query count anymore).
> multi table testbed

- computedfields/handlers.py
- example/test_full/tests/test_67.py
> fix model instance copying with empty pk

- README.md
- computedfields/__init__.py
- computedfields/handlers.py
- docs/manual.rst
- setup.py
Fixes #87.
@stephrdev I was not able to repro #87. Can you give more insights how this was triggered in your code? For all I tried, `kwargs['update_fields']` was either `None` or a `frozenset`. Which Django version are you using?
> fix update_fields in handler

- computedfields/models.py
- computedfields/resolver.py
- docs/examples.rst
- docs/manual.rst
- example/test_full/tests/test_localupdate_bulk.py
- example/test_full/tests/test_update_dependent.py
> remove (pre-) update_depedent_multi

- docs/examples.rst
- example/test_full/models.py
- example/test_full/tests/test_multitable.py
Fixes #93.
Note - this was not a bug in the code, but rather in the docs example. Fixed the docs and placed it as another test case.
> fix up-pulling docs and testcase

- computedfields/graph.py
- computedfields/helper.py
- computedfields/resolver.py
- example/exampleapp/tests.py
- example/requirements-ci.txt
- example/requirements-dev.txt
- example/test_full/models.py
- example/test_full/tests/test02_fkback.py
- example/test_full/tests/test_commands.py
- example/test_full/tests/test_helpermodels.py
- example/test_full/tests/test_proxymodels.py
Should fix #107.
@M-Saeb
It needs indeed additional fixes on the resolver maps, but it was straight forward to re-add the proxy models there. Could you check if this work for your case?
> fix proxy models

- docs/manual.rst
> docs about fexpressions

- example/exampleapp/tests.py
Should fix mysql error in https://github.com/netzkolchose/django-computedfields/actions/runs/3901256434/jobs/6666241005.
> fix ci for mysql

- computedfields/resolver.py
**ISSUE IN GENERAL:**
method `_querysets_for_update` uses OR to combine multiple statements to fetch records to update by dependencies. 
This way of selecting prevents the database from index usage for multiconditional where statements. That can dramatically reduce performance on not small tables.
We should avoid ORs. 
**MY CASE/CASE STUDY [Django 4.2, Postgres 13+]:**
For each A creation, the library generated a query like that:
```
SELECT DISTINCT
...
FROM "A"
LEFT OUTER JOIN "B"
ON ("A"."id" = "B"."a_id")
LEFT OUTER JOIN "C"
ON ("A"."id" = C."a_id")
WHERE
"B"."some_indexed_field_id" = XYZ OR C."a_id" = XYZ
```
All used fields here have btree indexes, but of course, Postgres can't use them in this scenario, because of the OR statement. So he did a full table scan for each query, which …
> Performance improvement: _querysets_for_update - generates queries that make database unable to use Indexes in multiconditional where statements.  

- computedfields/handlers.py
- computedfields/resolver.py
- example/test_full/models.py
- example/test_full/tests/test_narrow_M2M.py
> better narrowing for m2m updates

- computedfields/helpers.py
- computedfields/resolver.py
- example/test_full/tests/test_related_optimization.py
PR to add #132.
@BezBartek FYI - closed your PR due to branch naming conflicts.
> Optimal query combine

- .github/workflows/build.yml
- example/requirements-ci-psycopg3.txt
- example/requirements-ci.txt
- example/requirements-rtd.txt
fix docs build version deps, re-order task cases in CI
> fix docs build

- .github/workflows/build.yml
- example/requirements-ci-psycopg3.txt
- example/requirements-ci.txt
- example/requirements-dev.txt
- example/requirements-rtd.txt
- setup.py
Updated constraints for build tools
> Support for Django 5.2

- docs/manual.rst
> document related manager handling
